### ISSUE TITLE
Is it possible to define a bool in the config file?

### ISSUE THREAD

**Issue by raspberry-jenshen** [TatsuUkraine/dart_environment_config#21]
Hey, awesome package!

Have a question:

Is it possible to define a bool in the config file?

```
environment_config:
  path: environment_config.dart

  fields:
    fake_api:
      type: bool
      const: TRUE
      default: false
      config_field: TRUE
      static: TRUE
```

Currently, it crashes during config parsing with an error 

`type 'bool' is not a subtype of type 'String'`

Thanks!

version: 2.2.2
